repos:
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.34.1
    hooks:
      - id: golangci-lint
  - repo: git://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
